import "./globals.css";
import Nav from "@/components/basic/Nav";
import Footer from "@/components/basic/Footer";
import AuthSessionProvider from "@/components/providers/SessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthSessionProvider>
          <Nav />
          {children}
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
